In [1]:
import numpy as np
import numpy.distutils.system_info as sysinfo
import platform

print(sysinfo.platform_bits)
print(platform.architecture())

64
('64bit', 'WindowsPE')


In [2]:
x = np.array([1, 2, 3, 4, 5])
print('x=')
print(x)
print(type(x))
print(x.dtype)
print(x.shape)

x=
[1 2 3 4 5]
<class 'numpy.ndarray'>
int32
(5,)


In [3]:
y = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print('y=')
print(y)
print(y.shape)
print(y.size)

y=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
12


In [4]:
"""
Create a NumPy array of strings containing the letters 'a' through 'j' (inclusive) of the alphabet. Then, use NumPy array attributes to print the following information about this array:

dtype of array
shape of array
size of array
The code you submit in the code editor below will not be graded. Use the results from your code below, along with what you remember from the previous video, to complete the quiz below the code editor.
"""

# create numpy array of letters a-j
letter_array = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print("Letter Array: ", letter_array)

# get dtype of array
print("The type of the array is: ", letter_array.dtype)

# get shape of array
print("The shape of the array is: ", letter_array.shape)

# get size of array
print("The size of the array is: ", letter_array.size)

Letter Array:  ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j']
The type of the array is:  <U1
The shape of the array is:  (10,)
The size of the array is:  10


In [5]:
X = np.zeros((3,4), dtype=int) # default dtype = float64
print('X=')
print(X)
print('dtype:', X.dtype)

X=
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
dtype: int32


In [6]:
X = np.ones((4,5))
print('X=')
print(X)
print(X.dtype)

X=
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64


In [7]:
X = np.full((4, 3), 5) # dtype takes implied type of fill number (second argument)
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X=
[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
X has dimensions: (4, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [8]:
X = np.eye(5)
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X=
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [9]:
X = np.diag([10, 20, 30, 50])
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)

X=
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]
X has dimensions: (4, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32


In [10]:
x = np.arange(10)
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

# specify start number
x = np.arange(4, 10)
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

# specify step size
x = np.arange(1, 14, 3)
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

x=
[0 1 2 3 4 5 6 7 8 9]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

x=
[4 5 6 7 8 9]
x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

x=
[ 1  4  7 10 13]
x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [11]:
x = np.linspace(0, 25, 10)
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

print(np.linspace(0, 25, 10, endpoint=False))

x=
[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [12]:
x = np.arange(20)
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

x = np.reshape(x, (4,5)) # NOTE: this is a numpy function, not a ndarray method
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

x = x.reshape((10, 2)) # NOTE: this is a method of the numpy.ndarray class
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

x=
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
x has dimensions: (20,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

x=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
x has dimensions: (4, 5)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

x=
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
x has dimensions: (10, 2)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [13]:
Y = np.arange(20).reshape((10,2))
print('Y=')
print(Y)
print('Y has dimensions:', x.shape)
print('Y is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

X = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print('X=')
print(X)
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

Y=
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Y has dimensions: (10, 2)
Y is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

X=
[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]
X has dimensions: (10, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [14]:
x = np.random.random((3,3))
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

X = np.random.randint(4, 15, (3, 2))
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

x=
[[0.19552095 0.61458682 0.51098374]
 [0.14361385 0.69985163 0.46129915]
 [0.63234528 0.98864146 0.99326911]]
x has dimensions: (3, 3)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64

X=
[[13  7]
 [10  8]
 [ 5  6]]
X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [15]:
X = np.random.normal(0, 0.1, size=(1000,1000))
print('X=')
print(X)
print('X has dimensions:', x.shape)
print('X is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

X=
[[ 0.03911409 -0.09741404 -0.09586588 ...  0.11967097  0.28702351
  -0.00391283]
 [-0.02932211 -0.18778229  0.02963665 ...  0.07920038  0.0528568
  -0.22525733]
 [-0.19655509 -0.17747156  0.11733629 ... -0.07555932 -0.09701778
  -0.02108749]
 ...
 [-0.16208477  0.13045784  0.01238167 ...  0.10373811 -0.08322113
  -0.07750374]
 [ 0.00908481 -0.05863099 -0.20578368 ...  0.0172684  -0.0057982
  -0.00479869]
 [-0.0431049  -0.12002692 -0.02408493 ... -0.08480493  0.0501605
   0.01078386]]
X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64



In [16]:
print('mean:', np.mean(X))
print('std:', np.std(X))
print('max:', np.max(X))
print('min:', np.min(X))
print('# positive:', (X > 0).sum())
print('# negative:', (X < 0).sum())

mean: 9.926159079184715e-05
std: 0.09996591709745922
max: 0.46656257669583745
min: -0.4619822939803208
# positive: 500026
# negative: 499974


In [17]:
x = np.array([1, 2, 3, 4, 5])
print('x=')
print(x)
print()

print('1st element:', x[0])
print('2nd element:', x[1])
print('5th element:', x[4])
print()

print('1st element:', x[-5])
print('2nd element:', x[-4])
print('5th element:', x[-1])
print()

x[3] = 20
print(x)
print()

x=
[1 2 3 4 5]

1st element: 1
2nd element: 2
5th element: 5

1st element: 1
2nd element: 2
5th element: 5

[ 1  2  3 20  5]



In [18]:
X = np.arange(1, 10).reshape(3, 3)
print('X=')
print(X)
print()

print('Element at (0, 0):', X[0, 0])
print('Element at (0, 1):', X[0, 1])
print('Element at (2, 2):', X[2, 2])
print()

X[0, 0] = 20
print('X=')
print(X)
print()

X=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at (0, 0): 1
Element at (0, 1): 2
Element at (2, 2): 9

X=
[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]



In [19]:
x = np.array([1, 2, 3, 4, 5])
print('x=')
print(x)
print()

# Delete the first and last element of x
x = np.delete(x, [0, 4])
print('x=')
print(x)
print()

Y = np.arange(1, 10).reshape(3, 3)
print('Y=')
print(Y)
print()

# Delete the first row of Y
W = np.delete(Y, 0, axis=0)
print('W=')
print(W)
print()

# Delete the first and last column of Y
V = np.delete(Y, [0, 2], axis=1)
print('V=')
print(V)
print()

x=
[1 2 3 4 5]

x=
[2 3 4]

Y=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

W=
[[4 5 6]
 [7 8 9]]

V=
[[2]
 [5]
 [8]]



In [20]:
x = np.array([1, 2, 3, 4, 5])
print('x=')
print(x)
print()

# Append the int 6 to x
x = np.append(x, 6)
print('x=')
print(x)
print()

# Append the ints 7 and 8 to x
Y = np.append(x, [7, 8])
print('x=')
print(x)
print()

Y = np.array([[1,2,3],[4,5,6]])
print('Y=')
print(Y)
print('Y shape:', Y.shape)
print()

# Append a row containing 7, 8, 9 to Y
print('Insert array shape:', np.array([[10, 11, 12]]).shape)
W = np.append(Y, [[7,8,9]], axis=0)
print('W=\n')
print(W)
print()

# Append a column continaing 9 and 10 to Y
print('Insert array shape:', np.array([[10], [11], [12]]).shape)
V = np.append(Y,[[9],[10]], axis=1)
print('V=')
print(V)
print()

x=
[1 2 3 4 5]

x=
[1 2 3 4 5 6]

x=
[1 2 3 4 5 6]

Y=
[[1 2 3]
 [4 5 6]]
Y shape: (2, 3)

Insert array shape: (1, 3)
W=

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Insert array shape: (3, 1)
V=
[[ 1  2  3  9]
 [ 4  5  6 10]]



In [21]:
x = np.array([1, 2, 5, 6, 7])
print('x=')
print(x)
print()

# Insert the ints 3 and 4 before x[2]
x = np.insert(x, 2, [3, 4])
print('x=')
print(x)
print()

Y = np.array([[1, 2, 3], [7, 8, 9]])
print('Y=')
print(Y)
print('Y shape:', Y.shape)
print()

# Insert a row, [4, 5, 6] before x[1,:]
print('Insert array shape:', np.array([4, 5, 6]).shape)
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print('W=')
print(W)
print()

# Insert a column with 0 and 1 before x[:, 1]
print('Insert array shape:', np.array([0, 1]).shape)
V = np.insert(Y, 1, [0, 1], axis=1)
print('V=')
print(V)
print()

# From the notes - Insert a column full of 5s between the first and second column
# v = np.insert(Y,1,5, axis=1)

x=
[1 2 5 6 7]

x=
[1 2 3 4 5 6 7]

Y=
[[1 2 3]
 [7 8 9]]
Y shape: (2, 3)

Insert array shape: (3,)
W=
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Insert array shape: (2,)
V=
[[1 0 2 3]
 [7 1 8 9]]



In [22]:
x = np.array([1, 2])
print('x=')
print(x)
print('shape:', x.shape)
print()

Y = np.array([[3, 4], [5, 6]])
print('Y=')
print(Y)
print('shape:', Y.shape)
print()

# Stack x on Y
z = np.vstack((x, Y))
print('z=')
print(z)
print('shape:', z.shape)
print()

# Stack x to the right of Y - reshape x in order to stack correctly
w = np.hstack((Y, x.reshape(2, 1)))
print('w=')
print(w)
print('shape:', w.shape)
print()

x=
[1 2]
shape: (2,)

Y=
[[3 4]
 [5 6]]
shape: (2, 2)

z=
[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)

w=
[[3 4 1]
 [5 6 2]]
shape: (2, 3)



In [23]:
X = np.arange(1, 21).reshape(4, 5)
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

z = X[1:4, 2:5]
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

z = X[1:, 2:] # same as above column given 4x5 array
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

z = X[:3, 2:]
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

z = X[:, 2] # make 1-dimensional slide
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

z = X[:, 2:3] # make 2-dimensional slice
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

X=
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
X has dimensions: (4, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
z has dimensions: (3, 3)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
z has dimensions: (3, 3)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
z has dimensions: (3, 3)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[ 3  8 13 18]
z has dimensions: (4,)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[[ 3]
 [ 8]
 [13]
 [18]]
z has dimensions: (4, 1)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [24]:
z = X[1:, 2:]
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

z[2, 2] = 555 # because z is a "view" on X, any modification to z will affect X (point to same memory)
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in x are of type:', z.dtype)
print()

print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

z=
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
z has dimensions: (3, 3)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]
z has dimensions: (3, 3)
z is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

X=
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]
X has dimensions: (4, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [25]:
X = np.arange(20).reshape(4, 5)
z = X[1:, 2:].copy()
z[2, 2] = 555

print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in z are of type:', z.dtype)
print()

print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

z=
[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]
z has dimensions: (3, 3)
z is an object of type: <class 'numpy.ndarray'>
The elements in z are of type: int32

X=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
X has dimensions: (4, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32



In [26]:
X = np.arange(20).reshape(4, 5)
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

indices = np.array([1, 3])
print('indices=')
print(indices)
print('indices has dimensions:', indices.shape)
print('indices is an object of type:', type(indices))
print('The elements in indices are of type:', indices.dtype)
print()

y = X[indices, :]
print('y=')
print(y)
print('y has dimensions:', y.shape)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)
print()

z = X[:, indices]
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in z are of type:', z.dtype)
print()

X=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
X has dimensions: (4, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

indices=
[1 3]
indices has dimensions: (2,)
indices is an object of type: <class 'numpy.ndarray'>
The elements in indices are of type: int32

y=
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
y has dimensions: (2, 5)
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32

z=
[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]
z has dimensions: (4, 2)
z is an object of type: <class 'numpy.ndarray'>
The elements in z are of type: int32



In [27]:
X = np.random.randint(1, 20, size=(50, 5))
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print()

row_indices = np.random.randint(0, 50, size=10)
print("random 10 indices are:", row_indices)

X_subset = X[row_indices, :]
print('X_subset =')
print(X_subset)
print('X_subset has dimensions:', X_subset.shape)
print('X_subset is an object of type:', type(X_subset))
print('The elements in X_subset are of type:', X_subset.dtype)
print()

X=
[[18 10  6  4  6]
 [13  1  1  8  5]
 [14 15  7  3 12]
 [11 14 11  5 17]
 [14 12 14  5  8]
 [14 15  4 12  9]
 [ 5 11  1 10  7]
 [ 4 14 12  5  1]
 [ 8 12 19 19 18]
 [10 19  5  6  1]
 [ 6 17 17 10 19]
 [10 15 17 14 17]
 [ 4  9 13 11 16]
 [ 4 17 14 17 19]
 [13  6 16  4 16]
 [14  6 11 10  2]
 [ 6  2  2  1  8]
 [ 8 19  1 15 14]
 [11  6  5  4  8]
 [14 13  4 19  3]
 [17  4 12  9  9]
 [ 8  7 19 19 15]
 [16  7  3 19 12]
 [19  5 13 14 10]
 [16 11 15  8 14]
 [ 5 12  1  1 19]
 [10  4  9 12  1]
 [ 8 19  7  5  9]
 [ 4 10 18 19  9]
 [ 6  1 13  5  6]
 [16  6 10 10  4]
 [11 16 15 19 19]
 [ 9  2  1 15 19]
 [ 3  3 19 12 17]
 [ 5  3 19 13 18]
 [ 9 12  8 13 13]
 [ 1  3  2 11  6]
 [17  1 11 18  4]
 [ 4 11  1  2  7]
 [ 3  2  6  4 14]
 [12  6  4  6 13]
 [ 7 16 17 11  4]
 [ 9  4  1 12 17]
 [19  7  6  7 13]
 [17  4 19  6  6]
 [14 14  6 17  6]
 [11  9  4  9 12]
 [ 5 13  2  7  1]
 [ 6  6 18 16  2]
 [14  5 11 19  1]]
X has dimensions: (50, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are 

In [28]:
X = np.arange(20).reshape(4, 5)
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

z = np.diag(X)
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in z are of type:', z.dtype)
print()

z = np.diag(X, k=1)
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in z are of type:', z.dtype)
print()

z = np.diag(X, k=-1)
print('z=')
print(z)
print('z has dimensions:', z.shape)
print('z is an object of type:', type(z))
print('The elements in z are of type:', z.dtype)
print()

X=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
X has dimensions: (4, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

z=
[ 0  6 12 18]
z has dimensions: (4,)
z is an object of type: <class 'numpy.ndarray'>
The elements in z are of type: int32

z=
[ 1  7 13 19]
z has dimensions: (4,)
z is an object of type: <class 'numpy.ndarray'>
The elements in z are of type: int32

z=
[ 5 11 17]
z has dimensions: (3,)
z is an object of type: <class 'numpy.ndarray'>
The elements in z are of type: int32



In [29]:
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

print('Unique values:')
print(np.unique(X))

X=
[[1 2 3]
 [5 2 8]
 [1 2 3]]
X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

Unique values:
[1 2 3 5 8]


In [30]:
X = np.arange(25).reshape(5, 5)
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in x are of type:', X.dtype)
print()

print('X[X > 10]:')
print(X[X > 10])
print()

print('X[X <= 7]:')
print(X[X <= 7])
print()

print('X[(X > 10) & (X < 17)]')
print(X[(X > 10) & (X < 17)])
print()

print('X[(X > 10) & (X < 17)] = -1')
X[(X > 10) & (X < 17)] = -1
print(X)
print()

X=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

X[X > 10]:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]

X[X <= 7]:
[0 1 2 3 4 5 6 7]

X[(X > 10) & (X < 17)]
[11 12 13 14 15 16]

X[(X > 10) & (X < 17)] = -1
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



In [31]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print('x & y intersection:', np.intersect1d(x, y))
print('x & y set difference (x not an element of y):', np.setdiff1d(x, y)) # NOTE: order of x & y matters - np.setdiff1d(y, x) -> [6, 7, 8]
print('x & y union:', np.union1d(x, y))

x & y intersection: [2 4]
x & y set difference (x not an element of y): [1 3 5]
x & y union: [1 2 3 4 5 6 7 8]


In [32]:
x = np.random.randint(1, 11, size=(10,))
print('x=')
print(x)
print()

print('SORT\nx=')
print(np.sort(x)) # sorts out of place - allocates memory for new array
print()

print('x unchanged after: np.sort(x)')
print(x) # x is not changed by sort FUNCTION call
print()

print('UNIQUE\nx=')
print(np.unique(x))
print()

print('METHOD SORT\nx=')
x.sort() # x is changed when called as a METHOD
print(x)
print()

x=
[7 4 8 5 4 1 4 8 8 5]

SORT
x=
[1 4 4 4 5 5 7 8 8 8]

x unchanged after: np.sort(x)
[7 4 8 5 4 1 4 8 8 5]

UNIQUE
x=
[1 4 5 7 8]

METHOD SORT
x=
[1 4 4 4 5 5 7 8 8 8]



In [33]:
X = np.random.randint(1, 11, size=(5,5))
print('X=')
print(X)
print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print()

print("Sorted - axis=0")
print(np.sort(X, axis=0))
print()

print("Sorted - axis=1")
print(np.sort(X, axis=1))
print()

X=
[[ 5 10  7  2  8]
 [ 2  8  7 10  5]
 [ 7  4  9  8  7]
 [ 9  8  3  9  3]
 [ 2  7  6  4  1]]
X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int32

Sorted - axis=0
[[ 2  4  3  2  1]
 [ 2  7  6  4  3]
 [ 5  8  7  8  5]
 [ 7  8  7  9  7]
 [ 9 10  9 10  8]]

Sorted - axis=1
[[ 2  5  7  8 10]
 [ 2  5  7  8 10]
 [ 4  7  7  8  9]
 [ 3  3  8  9  9]
 [ 1  2  4  6  7]]



In [34]:
########################################################
# Quiz 1:  Manipulating ndarrays
########################################################

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 == 1]
print(Y)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [35]:
x = np.array([1, 2, 3, 4])
print('x=')
print(x)
print()

y = np.array([5, 6, 7, 8])
print('y=')
print(y)
print()

print('x + y =')
print(x + y)
print(np.add(x, y))
print()

print('x - y =')
print(x - y)
print(np.subtract(x, y))
print()

print('x * y = ')
print(x * y)
print(np.multiply(x, y))
print()

print('x / y = ')
print(x / y)
print(np.divide(x, y))
print()

x=
[1 2 3 4]

y=
[5 6 7 8]

x + y =
[ 6  8 10 12]
[ 6  8 10 12]

x - y =
[-4 -4 -4 -4]
[-4 -4 -4 -4]

x * y = 
[ 5 12 21 32]
[ 5 12 21 32]

x / y = 
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]



In [36]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
print('X=')
print(X)
print()

Y = np.array([5, 6, 7, 8]).reshape(2, 2)
print('Y=')
print(Y)
print()

print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()

print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()

print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()

print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))
print()

X=
[[1 2]
 [3 4]]

Y=
[[5 6]
 [7 8]]

X + Y = 
 [[ 6  8]
 [10 12]]

add(X,Y) = 
 [[ 6  8]
 [10 12]]

X - Y = 
 [[-4 -4]
 [-4 -4]]

subtract(X,Y) = 
 [[-4 -4]
 [-4 -4]]

X * Y = 
 [[ 5 12]
 [21 32]]

multiply(X,Y) = 
 [[ 5 12]
 [21 32]]

X / Y = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]

divide(X,Y) = 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]



In [37]:
x = np.array([1, 2, 3, 4])
print('x=')
print(x)
print()

print('np.sqrt(x):')
print(np.sqrt(x))
print()

print('np.exp(x):')
print(np.exp(x))
print()

print('np.power(x, 2):')
print(np.power(x, 2))
print()

x=
[1 2 3 4]

np.sqrt(x):
[1.         1.41421356 1.73205081 2.        ]

np.exp(x):
[ 2.71828183  7.3890561  20.08553692 54.59815003]

np.power(x, 2):
[ 1  4  9 16]



In [38]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
print('X=')
print(X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()

print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()

print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()

print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()

print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()

print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))
print()

X=
[[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]



In [39]:
X = np.array([1, 2, 3, 4]).reshape(2, 2)
print('X=')
print(X)
print()

print('3 * X = \n', 3 * X)
print()

print('3 + X = \n', 3 + X)
print()

print('X - 3 = \n', X - 3)
print()

print('X / 3 = \n', X / 3)
print()

X=
[[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]



In [40]:
x = np.arange(4)
print('x=')
print(x)
print('x shape:', x.shape)
print()

Y = np.arange(12).reshape(3, 4)
print('Y=')
print(Y)
print('Y shape:', Y.shape)
print()

Z = np.arange(3).reshape(3, 1)
print('Z=')
print(Z)
print('Z shape:', Z.shape)
print()

print('x + Y = \n', x + Y)
print()

print('Z + Y = \n',Z + Y)
print()

x=
[0 1 2 3]
x shape: (4,)

Y=
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Y shape: (3, 4)

Z=
[[0]
 [1]
 [2]]
Z shape: (3, 1)

x + Y = 
 [[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]

Z + Y = 
 [[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]



In [41]:
# We create a rank 1 ndarray
x = np.array([1,2,3])

# We create a 3 x 3 ndarray
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

# We create a 3 x 1 ndarray
Z = np.array([1,2,3]).reshape(3,1)

# We print x
print()
print('x = ', x)
print()

# We print Y
print()
print('Y = \n', Y)
print()

# We print Z
print()
print('Z = \n', Z)
print()

print('x + Y = \n', x + Y)
print()
print('Z + Y = \n',Z + Y)


x =  [1 2 3]


Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Z = 
 [[1]
 [2]
 [3]]

x + Y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Z + Y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [42]:
########################################################
# Quiz 2: Broadcasting
########################################################

# Use Broadcasting to create a 4 x 4 ndarray that has its first
# column full of 1s, its second column full of 2s, its third
# column full of 3s, etc.. 

X = np.ones((4, 4)) * np.array([1, 2, 3, 4])
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [52]:
x = np.arange(4)
print('x=')
print(x)
print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)
print()

y = np.arange(3)
print('y=')
print(y)
print('y has dimensions:', y.shape)
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)
print()

print('x as 2-d array:')
print(np.reshape(x, (1, x.shape[0])))
print()

print('outer sum of x & y:')
print(x[:, np.newaxis] + y)

x=
[0 1 2 3]
x has dimensions: (4,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int32

y=
[0 1 2]
y has dimensions: (3,)
y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32

x as 2-d array:
[[0 1 2 3]]

outer sum of x & y:
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]
