# Udacity - Python

## NumPy

[Python Docs](https://docs.python.org/3/library/index.html)

[Python Reserved Words](https://docs.python.org/3/reference/lexical_analysis.html#keywords)

[PEP 8 - Style Guide for Python Code](https://peps.python.org/pep-0008/)

[PEP 257 - Docstring Conventions](https://peps.python.org/pep-0257/)

[Conda - Managing Environments](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

[NumPy Documentation](https://docs.scipy.org/doc/numpy-1.13.0/contents.html)

[NumPy for Beginners](https://numpy.org/devdocs/user/absolute_beginners.html#numpy-the-absolute-basics-for-beginners)

In [2]:
import time
import numpy as np

In [2]:
x = np.random.random(100000000)

# Case 1 - Average of a list of numbers without NumPy
start = time.time()
sum(x) / len(x)
print(time.time() - start)

# Case 2 - Average of a list of numbers with NumPy
start = time.time()
np.mean(x)
print(time.time() - start)

7.702284812927246
0.03905177116394043


### Why NumPy

* Speed
    * When performing operations on large arrays, NumPy can often perform several orders of magnitude faster than Python `list`s.
* Multidimensional Array Data Structures
    * Can represent vectors and matrices
    * NumPy is optimized for matrix operations and allows for efficient linear algebra operations necessary for machine learning
* Optimized Built-in Mathematical Functions
    * Allows for a variety of complex mathematical computations that are very fast and require little code (avoids looping)

[NumPy Array - Structure for Efficient Numerical Computation](https://inria.hal.science/inria-00564007/document)

### Creating `ndarray`s

`ndarray` - n-dimensional array

An `ndarray` is a multidimensional array of elements all of the same type.

`np.array()` is a function that returns an `ndarray`.

In [3]:
x = np.array([1, 2, 3, 4, 5])
print(f'x = {x}')
print(f'ndim = {x.ndim}')
print(f'shape = {x.shape}')
print(f'size = {x.size}')
print(f'type(x) = {type(x)}')
print(f'x\'s element type = {x.dtype}')

x = [1 2 3 4 5]
ndim = 1
shape = (5,)
size = 5
type(x) = <class 'numpy.ndarray'>
x's element type = int64


In [4]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f'Y = {Y}')
print(f'ndim = {Y.ndim}')
print(f'shape = {Y.shape}')
print(f'size = {Y.size}')
print(f'type(Y) = {type(Y)}')
print(f'Y\'s element type = {Y.dtype}')

Y = [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
ndim = 2
shape = (4, 3)
size = 12
type(Y) = <class 'numpy.ndarray'>
Y's element type = int64


In [5]:
z = np.zeros((2,3,4))
print(f'z = {z}')
print(f'ndim = {z.ndim}')
print(f'shape = {z.shape}')
print(f'size = {z.size}')
print(f'type(Y) = {type(z)}')
print(f'z\'s element type = {z.dtype}')

z = [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
ndim = 3
shape = (2, 3, 4)
size = 24
type(Y) = <class 'numpy.ndarray'>
z's element type = float64


##### Upcasting

All the elements of an ndarray must be of the same type, so when given a `list` of `int`s and `float`s, NumPy will *upcast* all the values to `float`s.

In [6]:
x = np.array([1, 2.5, 4])
print(f'x = {x}')
print(f'x\'s element type = {x.dtype}')

x = [1.  2.5 4. ]
x's element type = float64


In [7]:
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype=np.int64)
print(f'x = {x}')
print(f'x\'s element type = {x.dtype}')

x = [1 2 3 4 5]
x's element type = int64


### NumPy Arrays to File

In [8]:
x = np.array([1, 2, 3, 4, 5])
np.save('data/my_array', x)

y = np.load('data/my_array.npy')
print(f'y = {y}')
print(f'type(y) = {type(y)})')
print(f'y\'s element type = {y.dtype}')

y = [1 2 3 4 5]
type(y) = <class 'numpy.ndarray'>)
y's element type = int64


### Built-in Functions

##### `np.zeros`

In [9]:
X = np.zeros((3,4))

print()
print(f'X = {X}')
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

X has dimensions: (3, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


##### `np.ones`

In [10]:
X = np.ones((3,2))

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


##### `np.full`

In [11]:
X = np.full((2,3), 5)

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[5 5 5]
 [5 5 5]]

X has dimensions: (2, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


##### `np.eye`

Identiy matrix is a square matrix that has only 1s on its main diagonal and zeros everywhere else.

In [12]:
X = np.eye(5)

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

X has dimensions: (5, 5)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


`np.diag`

In [13]:
X = np.diag([10,20,30,50])

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

X has dimensions: (4, 4)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


##### `np.arange`

    np.arange([start, ]stop, [step, ]dtype=None)

Will create a rank 1 ndarray with consecutive integers between `start` and `stop` by `step`.

In [14]:
x = np.arange(10)

print()
print('x = ', x)
print()

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [0 1 2 3 4 5 6 7 8 9]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [15]:
x = np.arange(4,10)

print()
print('x = ', x)
print()

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)



x =  [4 5 6 7 8 9]

x has dimensions: (6,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [16]:
x = np.arange(1,14,3)

print()
print('x = ', x)
print()

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 1  4  7 10 13]

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


##### `np.linspace`

`np.linspace(start, stop, N)` returns `N` evenly spaced numbers over the *closed* interval `[start, stop]`.

In [17]:
x = np.linspace(0,25,10)

print()
print('x = ', x)
print()

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


In [18]:
x = np.linspace(0,25,10, endpoint=False)

print()
print('x = ', x)
print()

print('x has dimensions:', x.shape)
print('x is an object of type:', type(x))
print('The elements in x are of type:', x.dtype)


x =  [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimensions: (10,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: float64


##### `np.ndarray.reshape`

Returns an array containing the same data with a new shape. Can also call `np.reshape()` with the np.ndarray as the first argument.

In [19]:
Y = np.arange(20).reshape(4,5)

print()
print('Y = \n', Y)
print()

print('Y has dimensions:', Y.shape)
print('Y is an object of type:', type(Y))
print('The elements in Y are of type:', Y.dtype)


Y = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Y has dimensions: (4, 5)
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


In [20]:
X = np.linspace(0,50,10, endpoint=False).reshape(5,2)

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

X has dimensions: (5, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


### `np.random`

##### `np.random.random`

`np.random.random(shape)` creates an ndarray of the given `shape` with random floats in the half-open interal `[0.0, 1.0)`

In [21]:
X = np.random.random((3,3))

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[0.67390116 0.90583337 0.50403939]
 [0.54347531 0.52618938 0.09101764]
 [0.71418252 0.74298757 0.99428273]]

X has dimensions: (3, 3)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64


##### `np.random.randint`

`np.random.randint(start, stop, size=shape)` creates an ndarray of the given `shape` with random integers in the half-open interval `[start, stop)`.

In [22]:
X = np.random.randint(4,15,size=(3,2))

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)


X = 
 [[ 8  8]
 [11 11]
 [ 5 11]]

X has dimensions: (3, 2)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: int64


##### `np.random.normal`

`np.random.normal(mean, standard deviation, size=shape)` creates an ndarray with the given `shape` that contains random numbers picked from a `normal` (Gaussian) distribution with the given `mean` and `standard deviation`.

In [23]:
X = np.random.normal(0, 0.1, size=(1000,1000))

print()
print('X = \n', X)
print()

print('X has dimensions:', X.shape)
print('X is an object of type:', type(X))
print('The elements in X are of type:', X.dtype)
print('The elements in X have a mean of:', X.mean())
print('The maximum value in X is:', X.max())
print('The minimum value in X is:', X.min())
print('X has', (X < 0).sum(), 'negative numbers')
print('X has', (X > 0).sum(), 'positive numbers')


X = 
 [[ 0.15079676  0.01657599  0.09393722 ... -0.18043351 -0.15796687
  -0.17713851]
 [ 0.00668451  0.02218153  0.02517964 ...  0.15268125 -0.03034087
  -0.13554826]
 [ 0.12943853 -0.09855584 -0.07706611 ... -0.08087347  0.30575885
   0.16108723]
 ...
 [-0.1009199  -0.02566894  0.09549064 ... -0.04044195  0.04578552
  -0.17209083]
 [-0.12924378 -0.10773976  0.1741583  ...  0.13654792  0.11237254
  -0.04167921]
 [ 0.01598981 -0.05909841 -0.03042878 ... -0.08786858  0.02472976
   0.14552208]]

X has dimensions: (1000, 1000)
X is an object of type: <class 'numpy.ndarray'>
The elements in X are of type: float64
The elements in X have a mean of: 6.146608820301584e-05
The maximum value in X is: 0.4750467551349008
The minimum value in X is: -0.5125822697407844
X has 500012 negative numbers
X has 499988 positive numbers


### Accessing and Modifying Elements of `ndarray`s

##### 1-D array

In [24]:
x = np.arange(1,6)

print()
print('x = ', x)
print()

print('This is the First Element in x', x[0])
print('This is the Second Element in x', x[1])
print('This is the Last Element in x', x[4])
print()

print('This is the First Element in x', x[-5])
print('This is the Second Element in x', x[-4])
print('This is the Last Element in x', x[-1])


x =  [1 2 3 4 5]

This is the First Element in x 1
This is the Second Element in x 2
This is the Last Element in x 5

This is the First Element in x 1
This is the Second Element in x 2
This is the Last Element in x 5


In [25]:
x = np.arange(1,6)

print()
print('Original:\n x = ', x)
print()

x[3] = 20

print('Modified:\n x = ', x)


Original:
 x =  [1 2 3 4 5]

Modified:
 x =  [ 1  2  3 20  5]


##### 2-D array

Elements in rank 2 ndarrays can be accessed with 2 indices in the form `[row, column]`.

In [26]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print('X = \n', X)
print()

print('This is (0,0) Element in X:', X[0,0])
print('This is (0,1) Element in X:', X[0,1])
print('This is (2,2) Element in X:', X[2,2])


X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0,0) Element in X: 1
This is (0,1) Element in X: 2
This is (2,2) Element in X: 9


In [27]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print('Original:\n X = \n', X)
print()

X[0,0] = 20

print('Modified (0,0) Element:\n X = \n', X)


Original:
 X = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified (0,0) Element:
 X = 
 [[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


### Deleting Elements of `ndarray`s

`np.delete(ndarray, elements, axis)` deletes the given list of of `elements` from the given `ndarray` along the specified `axis`.

For rank 1 ndarrays, the `axis` keyword is not required. For rank 2 ndarrays, `axis=0` is used to select *rows*, and `axis=1` is used to select *columns*.

##### 1-D array

In [28]:
x = np.arange(1,6)

print()
print('Original x = ', x)

x = np.delete(x, [0,4])

print()
print('Modified x = ', x)


Original x =  [1 2 3 4 5]

Modified x =  [2 3 4]


##### 2-D Array

In [29]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])

print()
print('Original:\n Y = \n', Y)

# Delete first row of Y
w = np.delete(Y, 0, axis=0)

# Delete first and last column of Y
v = np.delete(Y, [0,2], axis=1)

print()
print('w = \n', w)

print()
print('v = \n', v)


Original:
 Y = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

w = 
 [[4 5 6]
 [7 8 9]]

v = 
 [[2]
 [5]
 [8]]


### Appending and Inserting into `ndarray`s

##### `np.append`

`np.append(ndarray, values, axis)` appends `values` to `ndarray` along the specified `axis`.

##### 1-D Array

In [30]:
x = np.array([1,2,3,4,5])

print()
print('Original x = ', x)

x = np.append(x, 6)

print()
print('x = ', x)

x = np.append(x, [7,8])

print()
print('x = ', x)


Original x =  [1 2 3 4 5]

x =  [1 2 3 4 5 6]

x =  [1 2 3 4 5 6 7 8]


##### 2-D Array

In [31]:
Y = np.array([[1,2,3],[4,5,6]])

print()
print('Original:\n Y = \n', Y)

V = np.append(Y, [[7,8,9]], axis=0)

print()
print(' V = \n', V)

W = np.append(Y, [[9],[10]], axis=1)

print()
print(' W = \n', W)


Original:
 Y = 
 [[1 2 3]
 [4 5 6]]

 V = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 W = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


##### `np.insert`

`np.insert(ndarray, index, elements, axis)` inserts the list of `elements` to `ndarray` right before the given `index` along the specified `axis`.

##### 1-D Array

In [32]:
x = np.array([1, 2, 5, 6, 7])

print()
print('Original:\nx =', x)

x = np.insert(x,2,[3,4])

print()
print('x =', x)


Original:
x = [1 2 5 6 7]

x = [1 2 3 4 5 6 7]


##### 2-D Array

In [33]:
Y = np.array([[1,2,3],[7,8,9]])

print()
print('Original:\n Y = \n', Y)

W = np.insert(Y,1,[4,5,6],axis=0)
print()
print('W = \n', W)

V = np.insert(Y,1,5,axis=1)
print()
print('V = \n', V)


Original:
 Y = 
 [[1 2 3]
 [7 8 9]]

W = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

V = 
 [[1 5 2 3]
 [7 5 8 9]]


### Stacking

In order to stack, the shape of the corresponding axis must match.

##### `np.hstack`

Returns a stacked array formed by stacking the given arrays in sequence horizontally (column-wise).

##### `np.vstack`

Returns a stacked array formed by stacking the given arrays in sequence vertically (row-wise).

##### 1-D Array

In [34]:
x = np.array([1,2])

y = np.array([[3,4],[5,6]])

print()
print('x = ', x)
print('x has dimensions:', x.shape)

print()
print('y = \n', y)
print('y has dimensions:', y.shape)

z = np.vstack((x,y))

w = np.hstack((y,x.reshape(2,1)))

print()
print('vstack:\n z = \n', z)

print()
print('hstack:\n w = \n', w)


x =  [1 2]
x has dimensions: (2,)

y = 
 [[3 4]
 [5 6]]
y has dimensions: (2, 2)

vstack:
 z = 
 [[1 2]
 [3 4]
 [5 6]]

hstack:
 w = 
 [[3 4 1]
 [5 6 2]]


### Slicing `ndarray`s

Slicing is a way to access subsets of ndarrays.

* ndarray[**start**:**stop**]
* ndarray[**start**:]
* ndarray[:**stop**]

Note that the **stop** index is *excluded*.

For multidimensional ndarrays, you usually have to specify the slice for each dimension of the array.

[NumPy - Indexing Routines](https://numpy.org/devdocs/reference/arrays.indexing.html#basic-slicing-and-indexing)

In [35]:
X = np.arange(20).reshape(4,5)

print()
print('X =\n', X)
print()

print('X[1:4,2:5]')
print('Z =\n', X[1:4,2:5])

print()
print('X[1:,2:]')
print('W =\n', X[1:,2:])

print()
print('X[:3,2:]')
print('Y =\n', X[:3,2:])

print()
print('X[2,:]')
print('v =', X[2,:])

print()
print('X[:,2] -> returns rank 1 ndarray')
print('q =', X[:,2])

print()
print('X[:,2:3] -> returns rank 2 ndarray')
print('R =\n', X[:,2:3])


X =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

X[1:4,2:5]
Z =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

X[1:,2:]
W =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

X[:3,2:]
Y =
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]

X[2,:]
v = [10 11 12 13 14]

X[:,2] -> returns rank 1 ndarray
q = [ 2  7 12 17]

X[:,2:3] -> returns rank 2 ndarray
R =
 [[ 2]
 [ 7]
 [12]
 [17]]


##### Slicing with `ndarray`s

We can also use one `ndarray` to make slices, select, or change elements in another `ndarray`.

In [36]:
X = np.arange(20).reshape(4,5)

indices = np.array([1,3])

print()
print('X = \n', X)
print()

print('indices = ', indices)
print()

Y = X[indices,:]

print('X[indices,:]')
print('Y = \n', Y)
print()

Z = X[:,indices]

print('X[:,indices]')
print('Z = \n', Z)


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

indices =  [1 3]

X[indices,:]
Y = 
 [[ 5  6  7  8  9]
 [15 16 17 18 19]]

X[:,indices]
Z = 
 [[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [37]:
X = np.random.randint(1,20, size=(50,5))
print('Shape of X is: ', X.shape)

row_indices = np.random.randint(0, 50, size=10)
print("Random 10 indices are: ", row_indices)

X_subset = X[row_indices,:]
print()
print('X_subset: \n', X_subset)

X_subset = X[row_indices[4:8],:]
print()
print('X_subset: \n', X_subset)


Shape of X is:  (50, 5)
Random 10 indices are:  [37 44 10 13 47 43  8 48 27 47]

X_subset: 
 [[ 7 19 13  1  6]
 [ 9 16  1 12 19]
 [17  9 14 11  8]
 [14 13  3  3  4]
 [10 13  7  4  3]
 [12  7  9 12 13]
 [ 9  2 11  2  8]
 [ 6 19  3  9  4]
 [17 12  7  8  4]
 [10 13  7  4  3]]

X_subset: 
 [[10 13  7  4  3]
 [12  7  9 12 13]
 [ 9  2 11  2  8]
 [ 6 19  3  9  4]]


##### Boolean Indexing

Boolean indexing allows us to select elements using logical arguments instead of explicit indices.

In [38]:
X = np.arange(25).reshape(5,5)

print()
print('X = \n', X)
print()

print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that are less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

X[(X > 10) & (X < 17)] = -1

print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that are less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]



##### `np.diag`

`np.diag(ndarray, k=N)` extracts the elements along the diagonal defined by `N`. `k=0` is the default and refers to the main diagonal. `k>0` are used to select elements in diagonals above the diagonal. `k<0` are used to select elements below the main diagonal.

In [39]:
X = np.arange(25).reshape(5,5)

print()
print('X = \n', X)
print()

print('k=0')
print('z =', np.diag(X))
print()

print('k=1')
print('y =', np.diag(X, k=1))
print()

print('k=-1')
print('w =', np.diag(X, k=-1))


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

k=0
z = [ 0  6 12 18 24]

k=1
y = [ 1  7 13 19]

k=-1
w = [ 5 11 17 23]


##### `np.unique`

`np.unique(ndarray)` returns the sorted unique elements of an array.

In [40]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])

print()
print('X = \n', X)
print()

print('The unique elements in X are:',np.unique(X))


X = 
 [[1 2 3]
 [5 2 8]
 [1 2 3]]

The unique elements in X are: [1 2 3 5 8]


##### `ndarray.sort`

`np.sort(ndarray)` (function) sorts the `ndarray` out of place, meaning that it doesn't change the orginal `ndarray` being sorted.

`np.ndarray.sort()` (method) sorts the `ndarray` in place meaning that the orginal array will be changed to the sorted one.

##### 1-D Array

In [41]:
x = np.random.randint(1,11,size=(10,))

print()
print('Original:\nx = ', x)

print()
print('Sorted x (out of place):', np.sort(x))

print()
print('x after sorting:', x)

x.sort()
print()
print('Sorted x (in place):', x)


Original:
x =  [ 5  9  4  5  3  6  4 10  6  2]

Sorted x (out of place): [ 2  3  4  4  5  5  6  6  9 10]

x after sorting: [ 5  9  4  5  3  6  4 10  6  2]

Sorted x (in place): [ 2  3  4  4  5  5  6  6  9 10]


##### 2-D Array

`np.sort(ndarray, axis=-1, kind=None, order=None)` returns a sorted copy of an array. The `axis` denotes the axis along which to short. It can take values in the range `-1` to `(ndim-1)`.

* `axis = -1`: Sorts along the **last** axis. In the case of a 2-D `ndarray`, the last axis value is `1`.
* `axis = None`: Flattens the array before sorting and returning a 1-D array.
* `axis = 0`: If specified for a 2-D array, will sort all of the rows within a column. Read `axis=0` as **"down"** and `axis=1` as **"across"**.
* `axis = 1` If specified for a 2-D array, sort all of the columns with a row.

In [42]:
X = np.random.randint(1,11,size=(5,5))

print()
print('Original:\nX = \n', X)
print()

print()
print('Sorted columns:\n', np.sort(X, axis=0))

print()
print('Sorted rows:\n', np.sort(X, axis=1))


Original:
X = 
 [[ 1  3  1  5  9]
 [ 3 10  3  2  1]
 [ 8  1  2  7  4]
 [ 4  8  5  1  3]
 [ 8  4  2  9  3]]


Sorted columns:
 [[ 1  1  1  1  1]
 [ 3  3  2  2  3]
 [ 4  4  2  5  3]
 [ 8  8  3  7  4]
 [ 8 10  5  9  9]]

Sorted rows:
 [[ 1  1  3  5  9]
 [ 1  2  3  3 10]
 [ 1  2  4  7  8]
 [ 1  3  4  5  8]
 [ 2  3  4  8  9]]


### Set Operations

In [43]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print()
print('x = ', x)

print()
print('y = ', y)

print()
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:', np.union1d(x,y))


x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


### Memory Management

##### Slice Views

When we perform slices on ndarrays and save them into new variables, the data is not copied into the new variable. For example,

    Z = X[1:4, 2:5]

the slice of the orginal array `X` is not copied into the variable `Z`. Rather `X` and `Z` are now just two different names for the *same* ndarray. We say that slicing only creates a *view* of the original array. That means if we make changes to `Z` you will be in effect changing the elements in `X` as well.

In [44]:
X = np.arange(20).reshape(4,5)

print()
print('X =\n', X)
print()

Z = X[1:4,2:5]

print()
print('Z =\n', Z)
print()

Z[2,2] = 555

print()
print('X =\n', X)
print()


X =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


Z =
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


X =
 [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18 555]]



##### `copy`

In order to create new ndarray, `nndarray.copy` can be used to return a copy of the ndarray.

If we want to create a new ndarray that contains a copy of the values in a slice, we can use `np.copy(ndarray)`.

In [45]:
X = np.arange(20).reshape(4,5)

print()
print('X =\n', X)
print()

Z = np.copy(X[1:4,2:5])

W = X[1:4,2:5].copy()

Z[2,2] = 555

W[2,2] = 444

print()
print('X =\n', X)

print()
print('Z =\n', Z)

print()
print('W =\n', W)


X =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


X =
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Z =
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]

W =
 [[  7   8   9]
 [ 12  13  14]
 [ 17  18 444]]


### Arithmetic Operations

##### Element-wise Operations - *Broadcasting*

Broadcasting is the term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes. When performing element-wise operations, the ndarrays must have the same shape or be broadcastable.

For basic mathematical operations, NumPy offers functional or operator approaches. For example, `np.add()` or `+` will work. The functions usually have options that can be tweaked with keywords.

[NumPy - Broadcasting](https://numpy.org/devdocs/user/basics.broadcasting.html)

##### 1-D Array

In [46]:
x  = np.array([1,2,3,4])
y = np.array([5.5, 6.5, 7.5, 8.5])

print()
print('x = ', x)

print()
print('y = ', y)
print()

print('x + y = ', x + y)
print('add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('divide(x,y) = ', np.divide(x,y))


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.18181818 0.30769231 0.4        0.47058824]
divide(x,y) =  [0.18181818 0.30769231 0.4        0.47058824]


##### 2-D Array

In [48]:
X = np.arange(1,5).reshape(2,2)
Y = np.linspace(5.5, 8.5, 4).reshape(2,2)

print()
print('X = \n', X)

print()
print('Y = \n', Y)
print()

print('X + Y = \n', X + Y)
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]
add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]
subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]
multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]
divide(X,Y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]


##### Additional Mathematical Functions

In [49]:
x = np.array([1,2,3,4])

print()
print('x = ', x)

print()
print('EXP(x) = ', np.exp(x))
print()
print('SQRT(x) = ', np.sqrt(x))
print()
print('POW(x,2) = ', np.power(x,2))


x =  [1 2 3 4]

EXP(x) =  [ 2.71828183  7.3890561  20.08553692 54.59815003]

SQRT(x) =  [1.         1.41421356 1.73205081 2.        ]

POW(x,2) =  [ 1  4  9 16]


##### Statistical Functions

In [3]:
X = np.arange(1,5).reshape(2,2)

print()
print('X = \n', X)
print()

print()
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))


X = 
 [[1 2]
 [3 4]]


Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]


##### Scalar Math - Broadcasting

In the below examples, NumPy is broadcasting `3` along the ndarray so that they have the same shape.

In [4]:
X = np.array([[1,2],[3,4]])

print()
print('X = \n', X)
print()

print('3*X = \n', 3*X)
print()
print('3+X = \n', 3+X)
print()
print('3-X = \n', 3-X)
print()
print('X/3 = \n', X/3)


X = 
 [[1 2]
 [3 4]]

3*X = 
 [[ 3  6]
 [ 9 12]]

3+X = 
 [[4 5]
 [6 7]]

3-X = 
 [[ 2  1]
 [ 0 -1]]

X/3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]


##### Arithmetic Operations - Broadcasting on Axis

In [5]:
x = np.array([1,2,3])
y = np.array([1,2,3]).reshape(3,1)

Z = np.arange(1,10).reshape(3,3)

print()
print('x = ', x)
print()

print('y = \n', y)
print()

print('Z = \n', Z)
print()

print('x + Z = \n', x + Z)
print()
print('y + Z = \n', y + Z)


x =  [1 2 3]

y = 
 [[1]
 [2]
 [3]]

Z = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

x + Z = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

y + Z = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [14]:
X = np.arange(1, 17).reshape(4,4)
y = np.array([1,2,3,4]).reshape(1,4)

print()
print('X = \n', X)
print()

print('y = \n', y)
print()

print('X*y = \n', X*y)
print()

print('The shape of X is:', X.shape)
print('The shape of y is:', y.shape)
print('np.dot(y, X) = \n', np.dot(y, X))


X = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

y = 
 [[1 2 3 4]]

X*y = 
 [[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]
 [13 28 45 64]]

The shape of X is: (4, 4)
The shape of y is: (1, 4)
np.dot(y, X) = 
 [[ 90 100 110 120]]
